### ISSUE TITLE
fix awkward wording

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#10]
The following text appears here http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#2378422-message-semantics  but also elsewhere.

"See ITI TF-2:Appendix Z.7 for handling guidance for Access Denied."

How about this instead:  "See ITI TF-2: Appendix Z.7 for guidance on Access Denied."

**Comment by DavidPyke** [comment]
That text is straight  from the PDF.  I can't change that here, that's a CR

**Comment by lukeaduncan** [comment]
This is minor enough to be worth making the change
