### ISSUE TITLE
ITI-119 quality of match

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.PDQm#100]
```
2:3.119.4.2.2.4 Quality of Match

The Patient Demographics Supplier shall convey the quality of each match based on strength of the particular result to the supplied Patient Resource. The mechanism for determining the confidence of match is considered a product specific feature and is not specified in this transaction. When doing so, it shall represent the confidence of a particular match within the bundle as a score attribute. See FHIR Relevance section http://hl7.org/fhir/R4/search.html#score
```

All the examples in `2:3.119.4.1.3 Expected Actions` refer to the match-grade extension, but I don't see it referred to in the response expected actions.  I see it in the profile for the response, so I think there just needs to be a link to that somewhere in the response expected actions to say it has to conform to that profile

**Comment by slagesse-epic** [comment]
Make sure we explicitly state the response shall conform to the response message.

**Comment by slagesse-epic** [comment]
Updated the response message semantics to explicitly require that the message conform to the PDQm Match Output Bundle Profile
