### ISSUE TITLE
odd disconnected sentence

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#103]
> 1:38.1.1.2 Patient Demographics Supplier
> The Patient Demographics Supplier shall publish an instance CapabilityStatement at the metadata endpoint following [ITI Appendix Z.3](https://profiles.ihe.net/ITI/TF/Volume2/ch-Z.html#z.3-capabilitystatement-resource) using the [FHIR capabilities interaction](http://hl7.org/fhir/R4/http.html#capabilities). All supported search parameters and search methods (GET, POST) shall be specified. The [search parameters defined in [ITI-78]](https://build.fhir.org/ig/IHE/ITI.PDQm/branches/match/ITI-78.html#23784121-search-parameters) shall be supported, other parameters may be supported. The [PDQm $Match Operation](https://build.fhir.org/ig/IHE/ITI.PDQm/branches/match/OperationDefinition-PDQmMatch.html) shall also be supported. A requirements CapabilityStatements is provided for the [Patient Demographics Supplier](https://build.fhir.org/ig/IHE/ITI.PDQm/branches/match/CapabilityStatement-IHE.PDQm.PatientDemographicsSupplier.html) that shows the query parameters and operations to be supported.
> 
> This capabilities response will typically include all of the capabilities inclusive of all grouped actors and additional functionality.
> 

Would seem better flow to start with the requirements CS, and then have a paragraph on instance?

**Comment by slagesse-epic** [comment]
I think so; I have made that change. Note that this language was already like that in main.
