### ISSUE TITLE
word order

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#106]
> This message represents a request to invoke the [$match on Patient FHIR operation](http://hl7.org/fhir/R4/patient-operation-match.html). It is sent from the Patient Demographics Consumer to the Patient Demographics Supplier.

is this better?

> This message represents a request to invoke the [$match operation on Patient Resource](http://hl7.org/fhir/R4/patient-operation-match.html). It is sent from the Patient Demographics Consumer to the Patient Demographics Supplier.

**Comment by slagesse-epic** [comment]
Change to "operation $match on Patient".
