### ISSUE TITLE
need an open issue

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#107]
make an open issue to track the hl7 improvements to $match. You can leave the text in volume 2, but also make an open issue also.

Note that [FHIR-37361](https://jira.hl7.org/browse/FHIR-37361) and [FHIR-40880](https://jira.hl7.org/browse/FHIR-40880) request an additional parameter for specifying that matches should only be returned when there is exactly 1 certain match.

**Comment by slagesse-epic** [comment]
Added #112
