### ISSUE TITLE
should we constrain optionality on POST

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#108]
Is it really important that we endorse, and thus require servers support, the additional method of invoking $match?

> When onlyCertainMatches and count are not used, the Patient Demographics Supplier may optionally supply the Patient Resource as the HTTP POST body without wrapping it in a Parameters Resource. Doing so is equivalent to supplying a Parameters resource containing the Patient resource in the resource parameter and no other parameters.

**Comment by lukeaduncan** [comment]
This is vague, but this is how the base operation provides documentation on the parameter which is implying the direct call without parameters:

Use this to provide an  entire set of patient details for the MPI to match against (e.g. POST a  patient record to Patient/$match).
