### ISSUE TITLE
search criteria provided?

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#109]
> 2:3.119.4.1.3 Expected Actions
The Patient Demographics Supplier shall return demographic records that reflect the match to all of the search criteria provided by the Patient Demographics Consumer.

**Comment by slagesse-epic** [comment]
I am not sure what the issue is here.

**Comment by slagesse-epic** [comment]
Look at usage of the phrase "the search criteria" and make consistent with the rest of the transaction.
