### ISSUE TITLE
inaccurate sentences

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#11]
http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#23784221-patient-resource-definition-in-the-context-of-query-patient-resource-response

This issue is not introduced by the move to IG format; it exists in the current PDF text...

See the first two sentences in the section below.

- "shown below?"    We must have deleted a table at some point and deferred to FHIR.
-  "detailed description of the message is provided here"   Not really.

Should we remove the first 2 sentences? or?

2:3.78.4.2.2.1 Patient Resource Definition in the Context of Query Patient Resource Response

The components of the Patient Resource with cardinality greater than 0 (as shown below) are required, and the detailed description of the message is provided here. All other attributes of the response are optional. The Patient Resource contained within the Query Patient Resource Response message is described at http://hl7.org/fhir/R4/patient.html and is not further constrained by this transaction.

**Comment by DavidPyke** [comment]
This would need to be a CR.  I can't fix that here as it's this isn't an actual project.

**Comment by lukeaduncan** [comment]
committee reopens

**Comment by JohnMoehrke** [comment]
removed the first two sentences. Mostly because we have no relevant constraints. 

changed URLs to the FHIR core, to the Patient structureDefinition defined in PDQm... now that we have one.

also found a few other places for cleanup.
