### ISSUE TITLE
search score

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#110]
is it clear what the value means with search score? It  is not clear to me that there is a defined meaning of the value. Is it always between 0 and 1?

**Comment by lukeaduncan** [comment]
This is the content from the FHIR page on the operation:

All patient records SHALL have a search score from 0 to 1, where 1 is the most certain match, along with an extension "[match-grade](http://hl7.org/fhir/R4/extension-match-grade.html)" that indicates the MPI's position on the match quality.

**Comment by JohnMoehrke** [comment]
I thought I looked there and didn't see anything like that... Thus, my error.
