### ISSUE TITLE
match cases

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#111]
The cases are amazingly complete, like that there are examples. The QA person in me wonders if there could be a coverage table that maps the case numbers to situations. given the large number of cases it is hard to know if everything is covered. If it is easy, then do it... but it is certainly not needed.

VERY low priority.

**Comment by slagesse-epic** [comment]
Are you asking for the test cases on the Test Plan to be matched with the cases in the request Expected Actions? Otherwise I am not sure what this is asking for.

**Comment by oliveregger** [comment]
@JohnMoehrke could the coverage between case numbers and situations be covered with the Requirment resource in development?  https://build.fhir.org/requirements.html

**Comment by JohnMoehrke** [comment]
You are too deeply reading what I was describing. I was just looking for a simple markdown table that show the variables among the various cases you have already defined, and showing each case number in the matrix. I don't know if this would work, I didn't try to make the matrix myself. I should have tried that and gave you the solution. 

My goal is to somehow give the reader a visual clue about the differences between all your cases, especially as you have so many cases defined.

As I indicated above, this is not important. You do not need to address this.
