### ISSUE TITLE
[Public-Comment] Review comments

### ISSUE THREAD

**Issue by RicardoQuintano** [IHE/ITI.PDQm#115]
Attached are the PDFs with our (Ricardo and Bas) review comments.

[2:3.78 Mobile Patient Demographics Query [ITI-78] - Patient Demographics Query for mobile (PDQm) v3..pdf](https://github.com/IHE/ITI.PDQm/files/13922279/2.3.78.Mobile.Patient.Demographics.Query.ITI-78.-.Patient.Demographics.Query.for.mobile.PDQm.v3.pdf)
[2:3.119 Patient Demographics Match [ITI-119] - Patient Demographics Query for mobile (PDQm) v3.0.0-c.pdf](https://github.com/IHE/ITI.PDQm/files/13922284/2.3.119.Patient.Demographics.Match.ITI-119.-.Patient.Demographics.Query.for.mobile.PDQm.v3.0.0-c.pdf)

**Comment by slagesse-epic** [comment]
For discussion:

- From Bas vd Heuvel: "One observation - there is a lot of duplication with mandatory text in this profile, a statement that the FHIR specification takes prevelance in the case of conflicts is advisable." - Should we try to cut down on text that duplicates FHIR?
- I think it is good to define the list of codes to be used in case of error. Or include a link where to find this info.

DSUBm define well these codes.

Spencer to resolve:

- [ ] From Bas vd Heuvel: 
"This is wrong. string searches are always case-insentive or match the start of the string and not the complete string (see https://www.hl7.org/fhir/search.html#string). This cannot be changed in the CapabililtyStatement. Keeping this in will make this FHIR server different from others and will not allow implementers to combine this functionality with other."
"The text in section https://profiles.ihe.net/ITI/PDQm/3.0.0-comment/ITI-78.html#23784121-search-parameters states this correctly."
- [ ] This sentence is not cleat to me. 

"populates its attributes" - What the Consumer populates?

- [ ] I think this line can be removed as it is also presented after the next sentence.
- [ ] The Parameter resource contains a Patient resource as one of the parameters. 
- [ ] But should it return an OperationOutcome for this case?

**Comment by slagesse-epic** [comment]
"I think it is good to define the list of codes to be used in case of error. Or include a link where to find this info. DSUBm define well these codes." - Find a reference to FHIR core to link to, but do not try an enumerate codes unless we have a specific case profiled.

**Comment by slagesse-epic** [comment]
"Requests a list of patients matching the supplied set of demographics criteria (example: ID or Name) from the Patient Demographics Supplier. "

Spencer to add GitHub issue to publications to fix older PDQ and PDQv3.

**Comment by slagesse-epic** [comment]
"A Resource Bundle is returned representing the zero result set. No Patient Resources are provided in the result, and any OperationOutcome Resources do not have `error` or `fatal` severity. [Example output](Bundle-ex-match-output-empty.html).
A Resource Bundle is returned representing the zero result set. No Patient Resources are provided in the result. The Patient Demographics supplier may, at its discretion, return an OperationOutcome explicitly indicating that no matches were found, but any OperationOutcome Resources returned do not have `error` or `fatal` severity. [Example output](Bundle-ex-match-output-empty.html)."

- This isn't quite right; OO should only be returned if the nature of the failure is consistent with what would happen in a search that would have returned results. 

Also consider tightening test script.
