### ISSUE TITLE
mothers MaidenName

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#12]
http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#23784222-mothers-maiden-name

Suggests changing this:

Patient Demographics Suppliers shall include the mother’s maiden name, if known, in an extension named mothers MaidenName. See http://hl7.org/fhir/R4/extension-patient-mothersmaidenname.html

to something like this:

Patient Demographics Suppliers shall include the mother’s maiden name, if known, in this extension:  http://hl7.org/fhir/R4/extension-patient-mothersmaidenname.html

**Comment by DavidPyke** [comment]
Done
