### ISSUE TITLE
Add a link to Appx M html

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#14]
PDQm adds a subsection to Vol 2 Appx M

This page, http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/appendixm.html, probably in the editor's box, should have a link to Vol 2 Appx M in html:  https://profiles.ihe.net/ITI/TF/Volume2/ch-M.html

**Comment by DavidPyke** [comment]
Done
