### ISSUE TITLE
Documentation of Must Support / R2

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#2]
The PDQm home page http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/index.html says "MHD uses Must Support in StructureDefinitions with the definition found in Appendix Z. This is equivalent to IHE use of R2.

Appx Z has this:  https://profiles.ihe.net/ITI/TF/Volume2/ch-Z.html#z.10-profiling-conventions-for-constraints-on-fhir.     R2 is defined.   "Must Support" is not mentioned .

Maybe the Index should say: "MHD uses Must Support in StructureDefinitions  This is equivalent to IHE use of R2 as defined in Appendix Z."  

Secondarily, we should enhance Appx Z to say that R2 as defined there is equivalent to Must Support as used in FHIR.

**Comment by DavidPyke** [comment]
I have updated the reference using your text (except changing it to PDQm).  Can you open an issue against the general profiles for the change to Appx Z?

**Comment by JohnMoehrke** [comment]
I don't think that Appendix Z should make that declaration. it is up to the IG to make that declaration. This is the rule that FHIR core has defined for Must Support, that an IG must declare it.

**Comment by lynnfel** [comment]
Yes, I agree an IG must declare it.  That is not what I am contesting here

I stand by my recommendation in the original submission of this issue above, so I won't restate it.
