### ISSUE TITLE
Recommend combining Figures 38.6-1 and 38.6-2

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PDQm#21]
Figures 38.6-1 and 38.6-2 show the same thing in slightly different ways. The first makes the facade of the PDQm Patient Demographics Supplier and PDQ patient demographics consumer more clear, while the second makes the transaction flow in this scenario more clear. I think it would be better to combine them into a single figure.

**Comment by JohnMoehrke** [comment]
seems good idea
