### ISSUE TITLE
3.78.4.2.2.1 SHOULD vs SHALL

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PDQm#22]
From https://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#23784221-patient-resource-definition-in-the-context-of-query-patient-resource-response

"The Patient Resource(s) contained within the Query Patient Resource Response message should conform to Patient Profile for PDQm."

Should this "should" be a "shall"?

**Comment by JohnMoehrke** [comment]
It is should. We have never forbidden non compliant resources to be returned. In MHD I added a warning to clients that they need to be robust to non compliant resources. This is simply part of Postel's Law.
