### ISSUE TITLE
Appendix M - FHIR IG vs IHE Publications

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PDQm#23]
It was decided that Appendix E.3 and Appendix Z should be published to profiles.ihe.net despite still being in trial implementation (but designated as such with a watermarked background). 

PDQm adds a section M.4 to appendix M. This is currently published as part of the IG:  https://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/appendixm.html

Should this be moved to profiles.ihe.net for consistency?

**Comment by JohnMoehrke** [comment]
added the M additions to main TI just as we did with appendix E from PIXm.
