### ISSUE TITLE
Forward text is added to Sec 4 Overview

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#3]
In PDQm (PDF) https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_PDQm.pdf, Section 38.4 Overview starts with 38.4.1 Concepts    

In the IG, http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/overview.html starts with the content from the Forward (usually content that is 'dropped' when we go from TI to FT).   If a reader is going through Vol 1, s/he navigates through 3 prior pages before getting to this introductory-type text

Suggestion:  Move this to the PDQm "Home" page.     Or, remove the "Forward" and "Intro to this supplement" headers and keep the text here

**Comment by lynnfel** [comment]
this is probably related to issue #17

**Comment by JohnMoehrke** [comment]
Lynn,

The IHE-FHIR guidance is that there is no throwaway text, outside of the open/closed page. The concept of an intro prior to the table of contents seems similar to the throwaway text in supplement form.
