### ISSUE TITLE
1:38.1 - add cross-profile transaction equivalence to existing TF?

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#30]
**Section Number** https://profiles.ihe.net/ITI/PDQm/actors_and_transactions.html

**Issue** 
PDQm points back to PDQ and PDQv3 transactions as equivalent
PDQV3 points to PDQ transaction as equivalent in Table 24.1-2 https://profiles.ihe.net/ITI/TF/Volume1/ch-24.html#24.1
PDQ has no similar info

**Proposed Change** 
Do we make them consistent or remove this mapping?

How about just pointing to the content we moved to Appendix M? https://profiles.ihe.net/ITI/TF/Volume2/ch-M.html#M.4

When we answer this, consider making the same choice for the PIX family, and then create a traditional CP.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
I think appendix M already does address the three way equivilance.

**Comment by JohnMoehrke** [comment]
wouldn't the resolution of #35 also satisfy this?

**Comment by lynnfel** [comment]
I agree that Appx M is fine.     Then, you can update https://profiles.ihe.net/ITI/TF/Volume1/ch-24.html#24.1 to point to Appx M, and either use the editor box mechanism to make the parallel updates to PDQ and PDQV3, or (when the text is written for PIXm), I can write a CP.

**Comment by JohnMoehrke** [comment]
Issue solution #35 and #29 have resolved this.
