### ISSUE TITLE
Appendix M content lost

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#31]
**Section Number** *n/a content is missing; see below

**Issue** The prior PDF version of PDQm contains an update to Vol 2 Appx M.  See page 28 in https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_PDQm_Rev2-2_TI_2020-08-28.pdf

I don't see that content here.   If we decided to omit it in the IG and CP it into the Appx M, or do something else in another way, then I forgot about it.

Note that there are some inaccuracies in the tables in Appx M (eg why is date of death listed?).  If we keep the content, then those should be fixed.

**Proposed Change** 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by slagesse-epic** [comment]
It looks like appendix M was moved to profiles.ihe.net for the resolution to #23

**Comment by JohnMoehrke** [comment]
https://profiles.ihe.net/ITI/TF/Volume2/ch-M.html#M.4

We likely need some reference from PDQm to this publication.

I think at this point any changes to appendix M would be thru normal CP process.

**Comment by JohnMoehrke** [comment]
#35 will be adding references to M as needed. Thus there is nothing more to do for this issue. The content was not lost.
