### ISSUE TITLE
Figure 38.6-2 is missing

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#36]
**Section Number** Figure 38.6-1

**Issue** Figure 38.6-2 is missing

**Proposed Change** *
The last sentence of Cross-Profile considerations reads, "The Patient Demographics Supplier may act as a proxy to an existing PDQ or PDQv3 environment as shown in Figures 38.6-1 and 38.6-2."

Figure 38.6-2 referred to in that sentence exists in the PDF but not in this IG.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
@DavidPyke Did you chose to combine these two diagrams into one?

I tend to like the new single diagram. Is there any concern with dropping the text reference to the diagram that does not exist?

**Comment by DavidPyke** [comment]
I did combine them, I should have adjusted the text.  I'll do that.
