### ISSUE TITLE
common home for FHIR version and Resource/FMM level info

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#4]
This is not a PDQm specific issue. 

http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/overview.html#1-38-4-overview contains the information about FHIR version number and the FMM level of resources used by the profile.

For consistency, where should this go in IGs published by IHE (if anywhere).  (sorry if this is a duplicate)

**Comment by DavidPyke** [comment]
These are HL7 definitions, I think the links that are there are appropriate.  We could move them to Appx Z but I'm not sure that adds value
