### ISSUE TITLE
 2: 3.78.4.1.3 suggested Improvement - Case 2

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#41]
**Section Number**  2: 3.78.4.1.3

**Issue** *clarify Case 2... there's one matching record...

**Proposed Change** 
**Case 2:** The Patient Demographics Supplier finds at least one patient record matching the criteria sent in the query parameters. One or more patient identifier domains are requested via the mechanism specified in Section 3.78.4.1.2.4, and Patient Demographics Supplier recognizes all domains.

HTTP 200 (OK) is returned as the HTTP status code.

The Patient Demographics Supplier performs its matching and returns a bundle as described in Case 1. The Patient Demographics Supplier eliminates identifiers from the result set which do not exist in the list specified per Section 3.78.4.1.2.4 (domains to be returned). If all entries in the list of patient identifiers are eliminated, which would leave the patient identifiers list empty, then the entry shall not be present in the response bundle.

Delete the last sentence, right???  the beginning of the case says there is at least one matching record

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
correct. Given that Case 2 is specifically one or more are found, then the last sentence is never applicable. Further the sentence structure is problematic. So agree to remove the sentence
