### ISSUE TITLE
Volume 1 Security Considerations gather the AuditEvent profiles

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#46]
For ease of finding the AuditEvent profiles, the Volume 1 Security Considerations section could itemize each of the AuditEvent profiles and point to their transaction specific security considerations definition.

**Comment by JohnMoehrke** [comment]
note if this is agreed, then I will add this issue to be addressed in the future in MHD. and include it in the supplement template.

**Comment by lynnfel** [comment]
I support this recommendation (cannot think of a better approach).

**Comment by JohnMoehrke** [comment]
no strong reaction on today call. will continue to discuss

**Comment by JohnMoehrke** [comment]
1. add link from volume 1 SC to the volume 2 SC sections
2. bring forward to volume 1 'hints' at authn/authz/audit requirements to be found in volume 2 (e.g. where volume 2 mentions IUA requirements, this should be mentioned in volume 1, where volume 2 defines audit messages, this should be mentioned in volume 1). Mentioning may be by http links.
