### ISSUE TITLE
fix typo in query paramters table

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#7]
http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#23784121-query-search-parameters

in the identifier row, definitions column, the backslash after urn:oid:2.16.840.1.113883.4.1\ does not exist in the PDF supplement

?identifier=urn:oid:1.2.3.4\|145&identifier=urn:oid:2.16.840.1.113883.4.1\|123456789

**Comment by DavidPyke** [comment]
fixed
