### ISSUE TITLE
make explicit url into a link

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#8]
ET [base]/Patient?<query>

In the query parameters table, identifier row, find the following text.  The URL should be the link to the text IT ITF-2: Appendix Z.2.2

 Please see (ITI TF-2:Appendix Z.2.2)[https://profiles.ihe.net/ITI/TF/Volume2/ch-Z.html#z.2-query-parameters] for use of the token data type for patient identifiers.

**Comment by lynnfel** [comment]
Also here:

http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#2378413-expected-actions

 (see [ITI TF-2:Appendix Z.4[(https://profiles.ihe.net/ITI/TF/Volume2/ch-Z.html#z.4-structuredefinition-resource)]).

**Comment by DavidPyke** [comment]
fixed
