### ISSUE TITLE
editorial:  bold cases

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#9]
http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#2378413-expected-actions

Make Case 1:   Case 2:  bold font, as in the PDF.  This follows a pattern for the  equivalent PDQv2 and v3 transactions

**Comment by lynnfel** [comment]
also here:  http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#2378433-expected-actions

**Comment by DavidPyke** [comment]
Done
