### ISSUE TITLE
PDQm should define search parameter combinations

### ISSUE THREAD

**Issue by vassilpeytchev** [IHE/ITI.PDQm#90]
**Is your feature request related to a problem? Please describe.**
If you don't define a minimum set of search parameter combinations, there is no expectation that a server will support any search parameter combinations.

**Describe the solution you'd like**
Add a set of search parameter combinations that provide the most likely way to obtain a match or change PDQm to profile the $match operation.

**Comment by JohnMoehrke** [comment]
What combinations would you like to see?

$match operation is an independent work item that is simply awaiting a resource that wants to develop it.

**Comment by JohnMoehrke** [comment]
should we just replicate the combinations from IPA on Patient?

**Comment by vassilpeytchev** [comment]
Sure, using the same combinations from IPA makes sense.
