### ISSUE TITLE
Patient Identifier Domain Restrictions in ITI-119

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.PDQm#94]
In PDQ, PDQv3, and PDQm ITI-78, we have the ability for the client to limit the search results to patients with an identifier issued by a particular patient identification domain. We do not have equivalent functionality in ITI-119. While a client could suggest that it is interested in a particular patient identification domain by including the assigning authority of that domain as an identifier system in the $match input parameters, the semantics of $match would not require the server to honor that request. Is this functionality needed in ITI-119?

**Comment by JohnMoehrke** [comment]
I don't think that this is a problem with $match, as the operation clearly puts the responsibility for finding the best match on the server. Where the meaning of best match is a policy, and not defined (and should not be defined). Thus, one could implement a server that is strict, but one could also implement a system that is not strict. This is indeed a reason why $match is seen as preferrable.
