### ISSUE TITLE
distinction between search and $match

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#96]
I found this comment by Cooper to be helpful, and possibly help us distinguish between search and $match in our work.

Cooper Thompson
[9:57 AM](https://chat.fhir.org/#narrow/stream/179190-united-states/topic/US.20Core.20guidance.20on.20.24match.20versus.20Patient.20query/near/396521870)
This isn't US Core's position, but I've generally suggested that you use [Patient.search](http://patient.search/) when you have an end user in front of a keyboard doing a search, and that end user can review the (possibly) multiple results and select the right one based on interaction with the patient or other information the user knows about the patient.

You'd use $match when you need to do a system-to-system query and need to get exactly one high threshold match to use in subsequent automated API calls (with no human in the loop).

There is some fuzziness here, like you could use $match for user-facing searching as well, but in general this is how I think of $match vs. [Patient.search](http://patient.search/).

**Comment by slagesse-epic** [comment]
I think this distinction is already covered by the comparison in section [1:38.1.2.3](http://build.fhir.org/ig/IHE/ITI.PDQm/branches/match/volume-1.html#138123-differences-between-the-mobile-patient-demographics-query-iti-78-and-patient-demographics-match-iti-119-transactions). In particular, the bullet points are intended to help the reader through this line of thinking. 

Are you finding something confusing or lacking about that section?
