### ISSUE TITLE
do not put in IPA Patient requirement

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PDQm#98]
https://github.com/IHE/ITI.PDQm/blob/40d29ed33568ffb884f037d38c87cc8b55bbb5e3/input/fsh/PDQmPatient.fsh#L2C4-L2C4

**Comment by slagesse-epic** [comment]
The notes I have from our discussion on 7/27/23 in Oakbrook state that the committee agreed to keep this requirement in PDQm with additional guidance on how to populate the identifier, which I have added in the linked Profile description. Thus, I do not think a change is needed here.
