### ISSUE TITLE
ITI-119 expected actions

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.PDQm#99]
```
2:3.119.4.1.3 Expected Actions

...

The Patient Demographics Supplier shall return all exact matches to the search parameters sent by the Patient Demographics Consumer; IHE does not further specify matching requirements.

The response provided by the Patient Demographics Supplier to the Patient Demographics Consumer is a list of matching patients from the Patient Demographics Supplier’s information source. The mechanics of the matching algorithms used are internal to the Patient Demographics Supplier and are outside the scope of this framework.
```

In the above sentence, I'm not sure what is covered by "search parameters."  Does this mean the supplier is required to check every element populated in the requested Patient resource?  Does this include all extensions?  Would an exact match include resources found that have additional elements?  Would there be special handling for null values to count as "exact?"

I'd lean towards not even having that sentence and just let the second one cover everything, but I think it's worth a short discussion if I'm thinking of it the wrong way.

**Comment by slagesse-epic** [comment]
I think that text was copied from ITI-78 and is probably not appropriate for ITI-119. I agree it should be removed.
